### ISSUE TITLE
Improve tabbed window behaviour

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-mac#108]
Our current tab handling is a bit of a hack.

To fully address that, though, we should have a clearer sense of what our desired tabbing behaviour is. as of 10.12 there's the idea of user tabbing preferences; basically the user can choose to have <kbd>cmd</kbd> + <kbd>N</kbd> always open windows as tabs, if they change a setting in System Preferences -> Dock. 

I _suspect_ we desire behaviour more like safari, where cmd+N always opens a new window, and cmd+T always creates a new tab in that window. But: I haven't thought about it much.

In any case, there's one concrete annoyance I have, currently: restoration of windows on application launch does not preserve the previous tabbing state. Any windows that were open as tabs are opened as windows.

**Comment by ryanbloom** [comment]
Was this resolved in #241?

**Comment by cmyr** [comment]
Yes, or at least the hack that I was mainly trying to document is no more. Thanks!
