### ISSUE TITLE
Interface for find and replace

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#179]
The current search interface needs to be extended to support more advanced search and replace functionality. We should discuss what the UI for this should look like.

I created a mockup for the GSoC proposal which provides a rough idea of how the user interface would need to be adapted. 
<img width="869" alt="mockup" src="https://user-images.githubusercontent.com/1239705/40132199-01fb7c66-58f1-11e8-87bd-877581fcc911.png">
This was just a first draft and is open for discussion.

The UI needs to support the following functionality:
- [x] Plain-text search
- [x] Search using regular expressions
- [x] Search options: ignore case, wrap around, whole words
- [x] Find next, Find previous, Find all (I forgot to add this in the mockup)
- [x] Replacement of search results (Replace next, Replace all)
- [x] Highlighting of search results
- [x] Show/hide replace panel

In the near future
- [x] Multiple search queries (https://github.com/google/xi-mac/pull/229)
    * Dynamically add more search fields
- [x] Different highlighting styles (eg. different colorization of search results) (https://github.com/google/xi-mac/pull/229)

Far future (probably out of scope)
- [ ] Different search scopes and locations (eg. search directory, workspace, all open files)
- [ ] Options for replace (preserve case)

**Comment by cmyr** [comment]
cc @nangtrongvuon

**Comment by nangtrongvuon** [comment]
That looks like what I had in mind. One thing I'd do differently is have Replace be a checkbox like TextEdit:
![TextEdit Menu](https://user-images.githubusercontent.com/12481747/40152762-c02ab82c-59b0-11e8-8d60-7cadf9a478cd.png)

Other than that, this looks exactly like what I had in mind. Would the highlight colors be pre-defined or themed to the user's preferences?

**Comment by scholtzan** [comment]
The idea is to have several search fields which can be added with the (+) button. I agree, this is might be unusual since it is not supported by other editors. 
But it might improve readability when working with more complex queries. For example, to investigate specific patterns in log files, one regex might get quite long and hard to understand: 
`(Connect to 192\.168\.\d{1,3}\.\d{1,3}|Connection to host 192\.168\.\d{1,3}\.\d{1,3} (failed|interrupted)|Reconnect to 192\.168\.\d{1,3}\.\d{1,3})`

Having the possibility to split it up might be helpful for users in some cases. However, they can still write it as one regex ( eg. if they overlook the option to have multiple search fields, ...).

**Comment by cmyr** [comment]
I think this is an interesting idea, and could definitely be worth exploring. If it's something we make possible at some point, we would want to make sure it doesn't make the UI any more complex in what will by far the most common case, which will almost certainly be single-expression search.

I think your design does a reasonable job with this; the single '+' to the right of the search field will be fairly unobtrusive in the default case.

I can definitely see this being useful in a log viewer.

We probably don't want to show the replace field all the time, but only when replace is active. Similarly for the `location` field. (This might've been implied, but I want to say it out loud).

I'm still not sure that multiple queries should be something we work on immediately, although I won't object if it's something you're excited about. (I defer to the implementor 😎.) To my mind it might make more sense as a stretch goal. In particular, doing it correctly would require us to resolve https://github.com/google/xi-editor/issues/650 in a way that lets us support an arbitrary number of custom background styles, and probably move to doing all style resolution in core.

It also isn't 100% obvious to me how replace should interact with multi-expression find; I could imagine us wanting to have the idea of an 'active' find group, with other groups being 'inactive'. This is probably more work than it's worth, though.

**Comment by scholtzan** [comment]
I think the replace field can be shown/hidden using the checkbox that @nangtrongvuon suggested.

The "redesigned" find logic in the core already considers support for multiple queries. But in order for the front-end to support them we need to resolve google/xi-editor#650. Though, I suppose that will happen in the not too distant future.

For now I'd say that all groups are active and could be replaced.

**Comment by vlovich** [comment]
This is super-useful for looking at logs (based on log analysis tools I’ve
built at Apple and seen internally at Google).

One suggestion I have is to consider how one might remove the nth query
quickly with a single click when there are multiple rather than needing to
manually erase the text (maybe an x inline in the text field Right
justified could remove the row altogether rather than just removing text as
regular?).  The reason is that if you have a bunch of rows and they’re too
cluttered (or the queries don’t make sense anymore) you may want to remove
some.

One other thing to consider is whether the replace is global for any match
or per query.

Finally, if you want to make this even more useful for log analysis, having
a quick access UI for saving/restoring/switching groups of queries at a
time would be great so teams can share the ones that make sense (previously
I would recommend a drawer but if I recall correctly those have fallen out
of favor in modern OSX HID guidelines.

This looks awesome Anna. Keep up the great work!
