### ISSUE TITLE
set up travis / CI for this repo

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-mac#260]
We don't have much in the way of testing on the mac side, but it would be nice if we had a simple travis script set up that would at least compile the editor and run what we have.

**Comment by AlanFoster** [comment]
I'll see what I can do 🤞

**Comment by cmyr** [comment]
@AlanFoster It's a bit more complicated then that.

The problem is that there's currently no way for us to compile xi-mac without compiling xi-core, because xi-core's compilation is handled by a build script in xi-mac.

I think a possible solution would be to make xi-core its own target, and then have a scheme that we use for CI that only builds xi-mac? But I'm not sure if this is the best bet, it would take some exploring.

**Comment by cmyr** [comment]
yep, thanks :)
