### ISSUE TITLE
Fail to open new file when xi is already started

### ISSUE THREAD

**Issue by francisl** [xi-editor/xi-mac#269]
Nothing happen when I try to open a file if the editor is already started.

### Step to reproduce
1. Start the editor with an open a file
2. then try to open a new  file either from the menu or from the command line

This is a new build with rust 1.29

I don't know if it's related to #268, 
the log file just says  `[ERROR] setup_logging returned error, logging disabled: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })` and I'm not sure why, I have full access.

**Comment by cmyr** [comment]
I can't reproduce this either, I'm really not sure what's going on.

If you run the editor from within Xcode, do you see anything useful in the logs there? The other log error is unrelated.

**Comment by francisl** [comment]
Ok I rebuilt everything after updating xcode and now it's working fine. 

Maybe there is a small thing that was breaking it, I wasn't outdated by much. So I guess I'll close it.
