### ISSUE TITLE
Move to a protocol-based interface for core

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-mac#275]
A refactor that's long overdue: just as we define a client interface in `Client.swift`, we should define a core interface. All the various core methods would be presented through this interface; behind the surface it would wrap something like the existing `CoreConnection` class.

This will make it easy for us to change how the core connection is managed at some point in the future, and will also let us write tests in xi-mac that don't need to spin up a real instance of the core.

**Comment by jkaan** [comment]
@cmyr Hi there! I could pick this one up. Would it for now just involve putting the public interface of the `CoreConnection` into a protocol and typehinting to that interface instead of the concrete implementation?

**Comment by cmyr** [comment]
`CoreConnection` doesn't really have a typed interface at all; it just exposes functions for sending raw arbitrary RPCs. What we'd really like is to have a protocol that describes the legal, existing RPCs, and then implements that for `CoreConnection` by translating them into the raw RPCs.

We might also consider having a protocol for the `CoreView` interface, which describes just the RPCs that are scoped to a view.

There is a lot of RPC surface area (especially considering all of the movement commands) so I think it would be okay to go halfway, initially; for instance you could have a protocol method "raw_notification" that still lets you specify a command by it's (string) method name.

**Comment by cmyr** [comment]
oh, also: there was an earlier attempt at something like this, in `Dispatcher.swift`. This predates my involvement in the project, and doesn't seem to have really ever been consistently used; I would expect this new work to also result in us removing that file, I think?

**Comment by cmyr** [comment]
closed by #350.
