### ISSUE TITLE
when built from Xcode, display commit # in titlebar (or something?)

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-mac#279]
I consistently have several versions of xi-mac running, and I am regularly confused about which is which. It would be great if, when build from Xcode, xi-mac could display the HEAD hash in the menubar, or could inject an alternate app icon or something like this.

**Comment by jansol** [comment]
I'd say make it specific to Debug builds (aren't those the default when building from Xcode? [seems to be easy to detect too](https://stackoverflow.com/questions/25916396/how-to-identify-if-swift-was-compiled-with-optimization)) Alternatively there might be a way to define variants of assets (i.e. app icon) based on build type (á la xamarin), or just a custom resource copy step to choose the right icon manually.

**Comment by nangtrongvuon** [comment]
It could a part of the status bar, similar to Atom and VSCode in some sense.

**Comment by terhechte** [comment]
I gave this a go in this PR:
https://github.com/xi-editor/xi-mac/pull/289

**Comment by cmyr** [comment]
closed in #289
