### ISSUE TITLE
Add menu option to select language

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-mac#282]
This ~will depend on https://github.com/xi-editor/xi-editor/issues/863 and is related to https://github.com/xi-editor/xi-editor/issues/866; and the two might be worked on together.~ is ready!

This menu should be populated when the `available_languages` notification is received, shortly after startup. Selecting a language from this menu should apply a checkmark indicator, and should send the `set_language` RPC (described in 866 above).

**Comment by akxcv** [comment]
Hello, this is the number 1 option that I felt should already be there and very sad that it's missing. I'd be happy to implement this!

**Comment by cmyr** [comment]
@akxcv it's all yours, everything else should be in place, and it's an excellent warm-up issue!

**Comment by cmyr** [comment]
Had mis-scoped this project a little bit; this is currently blocked on #891

**Comment by akxcv** [comment]
What a lovely warmup!
