### ISSUE TITLE
Updated Icon

### ISSUE THREAD

**Issue by terhechte** [xi-editor/xi-mac#291]
As discussed in https://github.com/xi-editor/xi-mac/pull/289, I've taken some time to create a new icon for xi-mac. Instead of trying to build something with a new symbol I decided to keep the `xi` letters as it looks pretty good and as it doesn't deviate too much from the original icon. I build a couple of different icons but ultimately decided on two very different ones to showcase here. I have a clear favorite, but what's life without choices. Colors on these icons can obviously be changed, there would even be the option to change the icon depending on the current color theme (i.e. dark or bright) though that's a separate discussion.

So, without further ado, here're the big variants of the icons:

**Note: Github scales the images in a way that makes them blurry. Click the images to see it in the proper unblurred way**

![screenshot 2018-10-06 at 11 09 25](https://user-images.githubusercontent.com/132234/46569660-5d095d80-c958-11e8-9746-9cd14c3c46df.png)

Here's a mock of what it would look like in a dock with an ugly background picture.

![screenshot 2018-10-06 at 11 13 40](https://user-images.githubusercontent.com/132234/46569705-f5074700-c958-11e8-91ec-608e9186912a.png)

Would love to hear feedback.

**Comment by cmyr** [comment]
Nice, I think both of these are an improvement on the current icon, although the current icon does have the nice quality of being bad enough to be almost not worth complaining about. 😄

Of these, I prefer the second; the first is punchier but fairly generic, and the second is more in line with other contemporary macOS icons.

That said, I do think that in the distant future there is room for us to try and put some thought and energy into coming up with a more coherent visual identity; it might even be fun at some point to reach out to people in the design community, which is historically waaaay under represented in OSS.

**Comment by singularitti** [comment]
Just a personal opinion, so please do not take it too seriously. I think the second icon still have some aspects to improve.
1. The transitions in the following red rectangles look not so natural.
<img width="443" alt="screen shot 2018-10-06 at 10 22 55 pm" src="https://user-images.githubusercontent.com/25192197/46577500-a12b4b00-c9b6-11e8-9f94-5d39e432cd28.png">
Maybe it will be better if it looks like the Screenshot.app on macOS 10.14?
<img width="401" alt="screen shot" src="https://user-images.githubusercontent.com/25192197/46577569-6f66b400-c9b7-11e8-910c-df10d9f39b63.png">
2. The shade of the green rectangle looks so sharp that it stands out from other shade.
<img width="138" alt="shade" src="https://user-images.githubusercontent.com/25192197/46577598-e8fea200-c9b7-11e8-9b59-7ea3c449a3e6.png">
<img width="192" alt="other shades" src="https://user-images.githubusercontent.com/25192197/46577600-0df31500-c9b8-11e8-962f-65805a377276.png">

**Comment by terhechte** [comment]
@singularitti Sure. Both icons are rough versions, and I'd thought I'd improve on the final version as that iteration takes time. it is important to note that the big version of the icon is usually never what the people see. People mostly see the very small version. So that's where it should look good & sharp (not saying it currently does, but that's what I'd aim for).

**Comment by terhechte** [comment]
Would you think keeping the green theme on the second icon is fine or would it be interesting to have the second icon as a dark version? I feel like most current editors are darkish/blueish in their icons (lest MacVim which is greenish but also not really pleasing)

**Comment by cmyr** [comment]
I think there's a practical benefit to being easy to distinguish from existing icons.

**Comment by cmyr** [comment]
Also @terhechte not sure if you've seen but here is some history: https://github.com/xi-editor/xi-editor/issues/51

**Comment by jansol** [comment]
Closing this in favor of the original icon issue due to lack of activity.
