### ISSUE TITLE
Add a context menu

### ISSUE THREAD

**Issue by jansol** [xi-editor/xi-mac#306]
This would provide an alternative way to access things like
* Toggle comments
* Basically everything from Edit->Transform
* Find (seeded with selection or clicked word?) and Replace
* Cut, Copy & Paste

A context (right click) menu feels like a particularly natural way to issue commands that operate on selections, particularly when using the mouse to select text. This should also show the same key equivalents as the corresponding Edit menu entry (where applicable).

**Comment by AlanFoster** [comment]
I'll try taking a look at this :+1: I'm not an ios/swift developer, so this may take a bit of time for me

**Comment by cmyr** [comment]
@AlanFoster cool, feel free to ask Qs here if you get stuck.

**Comment by AlanFoster** [comment]
@MartinJrP Go ahead :+1:

**Comment by cmyr** [comment]
@MartinJrP welcome, look forward to a PR! If you have any questions about process or anything else feel free to drop by http://xi.zulipchat.com. ✌️
