### ISSUE TITLE
Add CLI so xi can be used as your $EDITOR

### ISSUE THREAD

**Issue by mads-hartmann** [xi-editor/xi-mac#313]
I want to start using xi for smaller text-editing tasks just to see how it feels. Specifically I want to use it to edit git commit messages.

xi currently bundles a `xi` bash script that simply invokes `open -a XiEditor "$@"`. To be able to use this as my git $EDITOR we'd need to extend it with a few more capabilities.

- Read from stdin
- Add a --wait flag. The `-W` flag to `open` doesn't quite get you all the way as it waits for the entire application to close rather than the window.

I'd be happy to help

**Comment by cmyr** [comment]
@mads-hartmann this is totally something we'd like, and if you wanted to explore that would be great! I'm not totally sure what would be involved, but I suspect it will require writing a custom little binary?

**Comment by mads-hartmann** [comment]
@cmyr Awesome, I'll have a look. I believe you're right, at least that's how Textmate [does it](https://github.com/textmate/textmate/blob/master/Applications/mate/src/mate.cc). I haven't written a single line of Rust before but I'll give it a go 😉

**Comment by cmyr** [comment]
@mads-hartmann Although rust is definitely a reasonable choice, I think swift would also make sense? This is going to be mostly interfacing with the mac app.

**Comment by mads-hartmann** [comment]
@cmyr Of course, you're right. Haven't written a single line of Swift either though 😉

**Comment by liamrosenfeld** [comment]
I've gotten a basic CLI written on my [fork](https://github.com/liamrosenfeld/xi-mac/tree/cli). It's currently able to open a given file in Xi. I'm still trying to figure out how to implement --wait.

**Comment by liamrosenfeld** [comment]
[Heres](#358) the CLI PR. It currently still needs --wait functionality.
