### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#327]
The syntax highlighting is incorrect for the second line in the document:

<img width="281" alt="screen shot 2018-11-03 at 12 08 57" src="https://user-images.githubusercontent.com/1239705/47956408-4824e780-df61-11e8-9679-c057e5cf4ef6.png">

All lines after that are highlighted correctly.

**Comment by cmyr** [comment]
@scholtzan that's definitely weird, what language is that? Is the syntax correct? Can you reproduce consistently?

a first thing to check with stuff like that is whether ST3 has the same behaviour, and you can also test with the `syncat` tool that comes with syntect; the latter is better but more annoying bc you have to download and build syntect. In any case this would tell us whether this is our bug or not.

**Comment by scholtzan** [comment]
The example is Scala, but it happens with other languages (Python, Rust, ...) too. 
ST3 renders it correctly.

**Comment by cmyr** [comment]
this is interesting, I've seen it once or twice but not consistently?

**Comment by scholtzan** [comment]
Huh, weird... If I run the newest version of https://github.com/xi-editor/xi-editor/pull/971, I can't reproduce it anymore.

**Comment by cmyr** [comment]
What commit were you having the initial issue with?

**Comment by scholtzan** [comment]
https://github.com/xi-editor/xi-editor/pull/971/commits/1a4b00c0088d56a54595f1d433b5327628387f6d

**Comment by cmyr** [comment]
Ah yea this is possibly related to auto-indent, if the highlighting isn't taking the auto-indent edit into account it might be referencing the wrong intervals when sending styles? I wouldn't expect that to be a problem, though.. 🤔

**Comment by scholtzan** [comment]
Okay, it doesn't happen on master. So probably just a problem with auto-indent.
