### ISSUE TITLE
Indicator for unsaved changes

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#365]
It would be useful to have some kind of indicator to show that files have unsaved changes. This would especially be useful when working on several files at the same time. Maybe there could be some kind of indicator in each file tab.

**Comment by scholtzan** [comment]
Yeah, it would be nice to see it for all open files, not just for the active one.

**Comment by jansol** [comment]
The file icon is also dimmed when there are edits, but yeah it's not visible when the window is not focused...

**Comment by rlziii** [comment]
I am currently in the process of working to fix this.  However, I am unsure what kind of indicator to display.  It seems as though tabs of an NSWindow cannot be stylized (it requires a String and does not allow for NSAttributedString), which throws away my initial idea of *italicizing* the titles of unsaved tabs.  I also considered simply adding " -- edited" at the end of each tab's title where appropriate; however, this is often truncated once the tab's title is too long.  I could alternatively add something like "(edited) " to the beginning of the tab's title, but it just doesn't seem right to me at the moment.  I even considered adding a discrete middle dot (`·`) character to the beginning of the tab's title.

Thoughts?

<img width="697" alt="screen shot 2018-12-30 at 02 40 32" src="https://user-images.githubusercontent.com/22179660/50545268-577c8600-0bdc-11e9-8b85-527cd27f2ec3.png">

<img width="697" alt="screen shot 2018-12-30 at 02 39 41" src="https://user-images.githubusercontent.com/22179660/50545270-6105ee00-0bdc-11e9-9c89-06ab3c94c28e.png">

<img width="697" alt="screen shot 2018-12-30 at 02 40 04" src="https://user-images.githubusercontent.com/22179660/50545271-66633880-0bdc-11e9-8268-84415a258261.png">

**Comment by jansol** [comment]
An indicator I see a lot is an asterisk (`*`) instead of a middle dot, but I admit the dot looks a bit cooler. Doesn't it have a larger variant too? This one is a bit too easy to overlook still.

**Comment by cmyr** [comment]
Hmm.

In the long term we would like to move away from NSDocument, and find another solution for tabs, so we can do something fancier then. I think that for now something simple is reasonable.

**Comment by rlziii** [comment]
I was able to find a "larger" middle dot in the form of a bullet (`•`).  For now I have opened a merge request with that symbol for the indicator.

**Comment by cmyr** [comment]
@rlziii cool, i'm just finishing up some other stuff but will be able to take a look shortly. Thanks!
