### ISSUE TITLE
Extra characters while inputting Tamil Text

### ISSUE THREAD

**Issue by SundarTM** [xi-editor/xi-mac#366]
While Inputting Tamil text with compound letters (கா, கி, etc.), Xi-editor generates additional characters.
The rpc log collected shows that xi-mac making redundant duplicate rpc calls for each compound character insertion.
This causes extra characters to be left in the text.

**Steps to recreate:**
- Enable Tamil99 Keyboard in Input sources
- Press following keys -> hqhslkf
- Expected text -> காகிதம் (U+0B95 U+0BBE U+0B95 U+0BBF U+0BA4 U+0BAE U+0BCD)
- Generated text -> ககாககிததம் (U+0B95 U+0B95 U+0BBE U+0B95 U+0B95 U+0BBF U+0BA4 U+0BA4 U+0BAE U+0BCD)

**Logs:**
The duplicate calls are marked bold.
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"க"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கா"}}}
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}**
**{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கா"}}}**
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"க"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கி"}}}
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}**
**{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"கி"}}}**
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"த"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"தம"}}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"தம்"}}}
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}**
**{"method":"edit","params":{"method":"delete_backward","view_id":"view-id-2","params":[]}}  
{"method":"edit","params":{"method":"insert","view_id":"view-id-2","params":{"chars":"தம்"}}}**

**Comment by cmyr** [comment]
Okay looking at this a bit more, there's something strange happening in our IME handling: our fn `replaceCharactersInRange:` is being called twice, first by `setMarkedText` and then again by `insertText`; and since the actual insertion is handled in `replaceCharactersInRange`, that's being called twice as well.

The next step here is to go re-read whatever docs are available on the `NSInputClient` protocol, to figure out exactly what the expected behaviour of these two functions is, and update them accordingly.
