### ISSUE TITLE
Populate new config file with defaults

### ISSUE THREAD

**Issue by jansol** [xi-editor/xi-mac#375]
Currently when no config file is present and the user hits `cmd+,` xi-mac appears to do nothing and silently creates an empty config file. Instead, it should create a config file with the current config and open that.

**Comment by jansol** [comment]
Speaking of which, we probably should either a) switch the config file name to something ending in `.toml` or b) move to NSUserDefaults and a config GUI like a proper macOS application.

**Comment by cmyr** [comment]
yea, it would be nice if we had something like json-schema so that we could autocomplete config values / provide validation, at least.

**Comment by mb21** [comment]
The file `~/Library/Application Support/XiEditor/preferences.xiconfig` seems to be created on install or something and it is populated. However, if you remove it and then open the editor preferences, the file is recreated but is indeed empty.

**Comment by cmyr** [comment]
@mb21 this is being addressed in #471. 🙏
