### ISSUE TITLE
Scrolling with an external mouse is very janky

### ISSUE THREAD

**Issue by jansol** [xi-editor/xi-mac#411]
When scrolling with the wheel of an external mouse, instead of smooth scrolling like when swiping on the touchpad, I get a couple of "ticks", then the view stops for a second, and then jumps to the final location.

It's a cheap wireless mouse and I use Scroll Reverser with it, but other applications don't have this problem so I doubt it's related to that.

**Comment by learning** [comment]
The `bounds.origin` didn't change when using the wheel on mouse, not sure why 🤔
[@EditViewController.swift Line 129](https://github.com/xi-editor/xi-mac/blob/master/Sources/XiEditor/EditViewController.swift#L129)

**Comment by nangtrongvuon** [comment]
@jansol Do you know the DPI of this mouse and the sensitivities you had? I'll try to look into this.

**Comment by jansol** [comment]
@nangtrongvuon Sorry, your comment shomehow slipped by me. The mouse in question is [this one](https://www.sanwa.co.jp/product/syohin.asp?code=MA-BTBL29R) (Japanese only, unfortunately) and I've been using it in its 1600 DPI mode.

**Comment by nangtrongvuon** [comment]
Have you tried scrolling on some other mouse? Perhaps its this one that's janky. I use a bunch of gaming mice and scrolling on xi feels fine to me. (Zowie FK2, Steelseries Kana V2, Logitech G305/G603, CM MasterMouse S)

**Comment by learning** [comment]
I have, Logitech G3 and G90, the same issue.

**Comment by nangtrongvuon** [comment]
Thanks for the reports, I'll investigate this when I have time.

**Comment by cmyr** [comment]
Yea I couldn't reproduce this either, but haven't dug in too deep.

**Comment by dimitre** [comment]
Similar issue here:

I'm using a microsoft optical mouse with wheel, and scrolling is truncated when using the wheel to scroll the text.
when using scrollbar it is smooth.
Thank you!

## Details
macOS 10.14.5
rustc 1.36.0 (a53f9df32 2019-07-03)
rustup

**Comment by cmyr** [comment]
@dimitre which commit are you on in `xi-mac`?

**Comment by nangtrongvuon** [comment]
@dimitre Hey, this should already be fixed with the latest `xi-mac` master.
