### ISSUE TITLE
git commit message not highlighted automatically

### ISSUE THREAD

**Issue by PhilCai1993** [xi-editor/xi-mac#425]
# Xi-Mac Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Details

_If your issue is a build or runtime error, please include the following:_
- macOS 10.14.1 
- commit id`6b9e13983b1ed6a862f0e2ad0d66ee54148b286f`

## Expected vs Actual
After set xi as git editor using `git config --global core.editor 'xi --wait'`, and when typing `git commit --amend`, the commit is displayed in XiEditor, but it's not highlighted using `git commit` syntax.

![image](https://user-images.githubusercontent.com/6828315/52117288-5365dd00-264e-11e9-8588-ee14431a7727.png)

actual: 👆(automatical)

expected 👇(manually selected view - language - git commit)

![image](https://user-images.githubusercontent.com/6828315/52117307-5fea3580-264e-11e9-83b0-712cc62873b3.png)

**Comment by cmyr** [comment]
@PhilCai1993 this should have been fixed recently, with https://github.com/xi-editor/xi-editor/issues/1096. Can you check this with master/master and see if it's still an issue?

**Comment by PhilCai1993** [comment]
@cmyr It works
