### ISSUE TITLE
Selections sometimes not rendered at the end of the line

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#434]
There are some issues with rendering selections. When selecting a paragraphs sometimes selections do not go until the end of some lines although they should be.

Here a screenshot of what is a single large selection with missing pieces in some lines (indicated in red):
<img width="739" alt="screenshot 2019-02-10 at 3 17 01 pm" src="https://user-images.githubusercontent.com/1239705/52541203-3a90b200-2d47-11e9-9cce-21f2571cb1f0.png">

**Comment by cmyr** [comment]
First question is whether these selections are being sent by core?

**Comment by scholtzan** [comment]
The selections sent by core look correct. In the screenshot case, core sent one selection annotation covering the whole range. So I guess it's more of a frontend rendering issue.

**Comment by ryanbloom** [comment]
Looks like it might have to do with calculating the width of non-ASCII characters? I notice all the problematic lines have a left or right quotation mark...

**Comment by cmyr** [comment]
Interesting observation @ryanbloom, doesn't really make any sense to me but sure looks suspicious.

**Comment by ryanbloom** [comment]
Okay, I did a little more research. Quotation marks and apostrophes are 3 bytes in UTF-8, while the rest of the characters in this example are 1 byte. So if the code mixes up characters with bytes somehow, it would be off by 2 character widths for every quote/apostrophe in the line it's processing. That seems consistent with @scholtzan's screenshot.

Most likely we're passing a character offset to a measurement function that expects a byte offset. Like... [here](https://github.com/xi-editor/xi-mac/blob/4082c2752bf7ae1c31dec9a63e52a5c980e4fdef/Sources/XiEditor/XiTextPlane/TextLine.swift#L273) maybe? Apple's documentation isn't really clear on what the parameters are supposed to mean; this is just a guess.

**Comment by scholtzan** [comment]
I found a way to fix it: https://github.com/xi-editor/xi-mac/pull/436 I am not entirely sure why it works that way though.
