### ISSUE TITLE
Allow modifying the line spacing

### ISSUE THREAD

**Issue by nhooyr** [xi-editor/xi-mac#450]
There doesn't seem to be any option to modify the font's line spacing.

**Comment by cmyr** [comment]
This is not currently supported, but thanks for bringing it up, not something I'd really thought about much.

**Comment by nhooyr** [comment]
I just added this to my fork. Will push soon.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
