### ISSUE TITLE
Look just like Xcode by default

### ISSUE THREAD

**Issue by nhooyr** [xi-editor/xi-mac#453]
By default, xi should look just as beautiful as Xcode.

Don't get me wrong, its beautiful by default but Xcode looks a lot nicer and I think for consistency on macOS, it's the way to go.

Issues before it can look like Xcode by default:
- [ ] #452 
- [ ] #450
- [ ] #456

**Comment by nhooyr** [comment]
Another issue here is the lack of a default cursor line like Xcode:

![IMG_0E2189D6305C-1](https://user-images.githubusercontent.com/10180857/54885525-14345b00-4e4b-11e9-8d7b-5e9c749126a7.jpeg)

**Comment by jansol** [comment]
By default, xi-editor should have its own identity.

Not sure if highlighting the current line(s) is possible yet, IIRC it is in sublime text though (which xi draws a lot of inspiration and its themes from). The other two issues look reasonable.

However I'd argue that looking *just* like Xcode out of the box is bad and would make everyone assume that it's exactly that, possibly including Apple. (and that could be trouble) If you want your xi-editor to look just like Xcode that's your choice, but it really shouldn't be the default.

**Comment by nhooyr** [comment]
> By default, xi-editor should have its own identity.

I think Xi should do its best to fit into the host OS by default, that's something most editors completely fail at imo and why I want to use xi. It's just beautiful. I think most of the Mac user base would appreciate it if Xi just looked like Xcode by default because Xcode looks even better.

So to be clear, I just think Xcode is by far the best looking editor I have ever seen and so I think Xi should look like it instead by default. Most macOS users will definitely appreciate this.

I strongly doubt apple will come after xi for this, just seems ridiculous as its not like this replaces Xcode or affects Xcode's usage.

**Comment by nangtrongvuon** [comment]
A lot of frontend features are made using XCode as an inspiration, but we can't look exactly like XCode (since they probably use some under the hood custom stuff). The cursor line is pretty doable, maybe I'll get to doing it soon.

**Comment by cmyr** [comment]
Xcode is certainly a good guideline for what a native macOS code editor looks like, but I don't feel obliged to match it precisely.

**Comment by jansol** [comment]
if there are more changes that should be done in order to match (the good parts of) Xcode, they probably deserve separate issues. Closing this.
