### ISSUE TITLE
autosave triggers

### ISSUE THREAD

**Issue by nhooyr** [xi-editor/xi-mac#455]
xi-mac should be continuously auto saving files.

**Comment by nhooyr** [comment]
IE the user shouldn't have to think about saving.

**Comment by nhooyr** [comment]
Just like Intellij/Xcode etc.

**Comment by jansol** [comment]
Xcode doesn't autosave...

**Comment by jansol** [comment]
It does save on exit and on build, yes, but not continuously. Save-on-close could be an option. Building from xi-mac is not possible yet so that part is irrelevant (and would probably be the responsibility of the plugin that deals with building).

**Comment by nhooyr** [comment]
My bad, I will clarify. I meant save on lost focus which `Xcode` does do and sublime has an option for as well and jet brains IDE's all do by default.

**Comment by jansol** [comment]
That sounds like a reasonable option. Can you update the issue title and OP to reflect this? Something like "more save triggers". Maybe add a list of checkboxes for the various save scenarios so we can use this as a tracking issue.

**Comment by jansol** [comment]
The most difficult part about this would be the config I think? The core does not know about focus and not all frontends will have a concept for it so I'm not sure where the setting would belong. @cmyr thoughts?

**Comment by jansol** [comment]
A timed autosave (every 5 minutes or whatever, might as well make it configurable) could also be okay. Personally I wouldn't use it in xi-mac, especially once state restoration is fully working, but it is a common feature in other applications and certainly holds value for some people.

**Comment by nangtrongvuon** [comment]
This doesn't seem too tricky - maybe overriding `windowWillResignKey` and calling save in XiWindow would work.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
