### ISSUE TITLE
Xcode colorscheme

### ISSUE THREAD

**Issue by nhooyr** [xi-editor/xi-mac#456]
See #453 

Right now the default theme is Github based. Imo Xcode's looks better.

This doesn't need to be the default but would be nice to include by default.

**Comment by cmyr** [comment]
This is certainly a reasonable project, and may be possible just by creating a custom theme with the current theme format; alternatively it may require us to add our own custom theme format, which is something in the 'eventually' pile.

**Comment by jansol** [comment]
There is also the question of what themes should we ship by default, which so far has not had much thought given to it.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
