### ISSUE TITLE
xi --wait does not return after application exit

### ISSUE THREAD

**Issue by ferranpujolcamins** [xi-editor/xi-mac#460]
- macOS 10.14.4
- the commit you're on #b55f1c0
- I run xi-mac with the following command: `xi --wait <file>`

When quitting xi-mac with the cmd+q keyboard shortcut, the cli does not terminate and keeps waiting.

**Comment by cmyr** [comment]
Can confirm. I think this is a recent regression, maybe something in fbe1fa0?
