### ISSUE TITLE
Status Bar hiding last line

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#475]
If the status bar is visible then it hides the last text line:
![out](https://user-images.githubusercontent.com/1239705/65069493-a40d1a80-d93f-11e9-9a0b-0dc547c18cc5.gif)

**Comment by nangtrongvuon** [comment]
@scholtzan This isn't a bug but more of a design decision. I opted for the "small bar at the bottom" design like VSCode or Sublime, and had it be as high as a line in 14px Inconsolata.

**Comment by scholtzan** [comment]
Right, what I meant is that the status bar overlaps with the last text line if I scroll to the bottom. So if I open a file that has text on the last line then I can't see that text line when I am at the end of the document. In Sublime and Xcode and what I would expect here is that when I scroll to the very bottom then the last line should appear above the status bar.

**Comment by nangtrongvuon** [comment]
Woops, my bad, didn't understand you clearly there. I'll look into this, which I think shouldn't be too hard of a fix - might just need to adjust a bit of the rendering code to compensate for the status bar.
