### ISSUE TITLE
Drag events cause file to be opened

### ISSUE THREAD

**Issue by guidorice** [xi-editor/xi-mac#480]
# Xi-Mac Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Details

OS X 10.14.6

## Expected vs Actual

Actual: I noticed that xi opens files which are dragged across it's window frame. This occurs even if the file is not released on the xi frame. This occurred to me several times when I was dragging files from the Finder into my email client. They just happened to cross the xi window frame.

Expected: xi should not open files unless they are released/dropped on it's frame.

PS thanks for this app! I love how fast and responsive it is.

**Comment by nangtrongvuon** [comment]
Huh, I'll investigate this. Thanks for the report.
